#
# !! Automatically generated by Ladle !!
# Compiled Jan 27 2017, 00:49:20
#
# Cookbook Name:: default
# Recipe:: default
#
# Copyright 2017, YOUR_COMPANY_NAME
#
# All rights reserved - Do Not Redistribute
#

